### PR TITLE
udpate 1.10.0

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by setu4993** [comment]
@conda-forge-admin, please rerender

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by setu4993** [comment]
Thanks @fhoehle! I think the different versions for v2 and v3 led to the bot not picking it up.

**Comment by fhoehle** [comment]
@setu4993 thanks for keep track of this PR. Next version of `avro` will give a deprecation warning when using `avro-python3`, because `python=2` will be dropped.

**Pull request merged**
