### PR TITLE
Bump to 1.8.1. Use an apache mirror rather than buggy pypi.

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
Re-ran appveyor manually

**Comment by mariusvniekerk** [comment]
You may need to rerender with the latest anvil

**Comment by kwilcox** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by ocefpaf** [comment]
The AppVeyor problem is because people removed the working solution we had (`The AppVeyor 'rollout builds'`, see https://github.com/conda-forge/conda-smithy/commit/d9b10cb20236da2c714e78aacaa7b7e252f7c40d)  and added an external layer that depends on more moving parts that are broken now.

Fixing is easy but fans of adding layers, and fragility to the system, are not keen an on easy fix.

**Comment by pkgw** [comment]
@ocefpaf So should maintainers just sit tight and wait for conda-smithy 2.2.1?

**Comment by ocefpaf** [comment]
> @ocefpaf So should maintainers just sit tight and wait for conda-smithy 2.2.1?

That is what I will do b/c any fast solution, like reverting to previous state that worked just fine without the unnecessary fix that broken, will probably hurt a few egos :unamused:

**Comment by kwilcox** [comment]
@mariusvniekerk 2.2.1 was released and I rerendered, should be good to go.

**Comment by mariusvniekerk** [comment]
Thanks

**Pull request merged**
